module.exports = {
  BHOST: 'http://localhost:5000',
  FHOST: 'http://localhost:3000',
  PORT: 5001,
  DATABASE: 'mongodb://127.0.0.1:27017/crm_data',
  JWT_SECRET: 'crmsecretkey',
  SENDGRID_API_KEY: 'ENTER YOUR API KEY HERE',
  EMAIL_JWT_SECRET: 'validemailsecretkey',
  CERT_PATH: '/home/bihan/crm/tweencraft_business_backend/ssl/698d1cf98a097ef.crt',
  KEY_PATH: '/home/bihan/crm/tweencraft_business_backend/ssl/tweencraft.com.key',
  CA: '/home/bihan/crm/tweencraft_business_backend/ssl/gd_bundle-g2-g1.crt',
  S3_ACCESS_KEY: 'ENTER YOUR ACCESS KEY HERE',
  S3_SECRET_ACCESS_KEY: 'ENTER YOUR SECRET ACCESS KEY HERE',
  BUCKET_NAME: 'ENTER YOUR BUCKET NAME HERE',
  ZOKO_API_KEY: 'ENTER YOUR ZOKO API KEY HERE',
};
